- hosts: meetup-hello-world
  become: true
  roles:
    - { role: unix_users, _unix: "{{ application_default }}" }
    - { role: docker_network, _docker_network: "{{ docker_network_default }}" }
    - { role: application, _application: "{{ meetup-hello-world }}" }