registry_host: "85.25.226.182"
meetup_hello_world_host: "{{ groups['meetup-hello-world'][0] }}"

docker:
  registry: "{{ registry_host }}:5000"
  version: "1.12.3-0~{{ ansible_lsb.codename|lower }}"
  default_registry: "--add-registry {{ registry_host }}:5000"
  insecure_registry: "--insecure-registry {{ registry_host }}:5000"
